version: "3.8"

networks:
  app_network:
    driver: overlay

services:
  frontend:
    image: frontend-app:latest
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    image: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    networks:
      - app_network

  api:
    image: mp4-to-gif-api:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    volumes:
      - ./storage:/storage
    networks:
      - app_network

  worker:
    image: mp4-to-gif-worker:latest
    deploy:
      replicas: 5
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    volumes:
      - ./storage:/storage
    networks:
      - app_network
